web:
  image: registry.inhouse.net:4043/mage19:7oct16a
  ports:
    - "8096:80"
  volumes:
    - ./htdocs:/var/www/htdocs
  links:
    - mysql
  env_file:
    - env
mysql:
  image: mysql:5.6.23
  env_file:
    - env
phpmyadmin:
  image: phpmyadmin/phpmyadmin
  links:
    - mysql
  ports:
    - 8196:80
  environment:
    MYSQL_USERNAME: root
    MYSQL_ROOT_PASSWORD: myrootpassword
    PMA_HOST: mysql
